export enum EmployeeStatusValueObject {
    STATUS_ACTIVE = 1,
    STATUS_INACTIVE = 10,
    STATUS_SUSPENDED = 20,
    STATUS_PENDING_VERIFICATION = 30,
    STATUS_TERMINATED = 40,
    STATUS_LIMITED = 50,
    STATUS_NEEDS_UPDATE = 60,
    STATUS_ON_HOLD = 70,
    STATUS_FLAGGED = 80,
    STATUS_VIP = 90,
}
